Revert "UPSTREAM: pstore: Use global ftrace filters for function trace filtering"
This reverts commit c824ceb13d5cd9ce1b99b4284982cab4b7841f69.

Reason for revert: This patch introduces a call to a function which is not available in chromeos-4.4, resulting in the following compile error if enabled.

fs/pstore/ftrace.c: In function pstore_ftrace_knob_write:
fs/pstore/ftrace.c:79:3: error: implicit declaration of function ftrace_ops_set_global_filter

Original change's description:
> UPSTREAM: pstore: Use global ftrace filters for function trace filtering
>
> Currently, pstore doesn't have any filters setup for function tracing.
> This has the associated overhead and may not be useful for users looking
> for tracing specific set of functions.
>
> ftrace's regular function trace filtering is done writing to
> tracing/set_ftrace_filter however this is not available if not requested.
> In order to be able to use this feature, the support to request global
> filtering introduced earlier in the series should be requested before
> registering the ftrace ops. Here we do the same.
>
> BUG=chromium:633355
> TEST=Boot 4.4 kernel on veyron or kevin/gru
>
> Change-Id: Ic000a7d4a4f598777cdfa707cacfe84ccbc8c653
> Signed-off-by: Joel Fernandes <joelaf@google.com>
> Signed-off-by: Kees Cook <keescook@chromium.org>
> Signed-off-by: Guenter Roeck <groeck@chromium.org>
> (cherry picked from commit 7a0032f50472)
> Reviewed-on: https://chromium-review.googlesource.com/440558
>

TBR=keescook@chromium.org,groeck@chromium.org
# Not skipping CQ checks because original CL landed > 1 day ago.
BUG=chromium:633355

Change-Id: I086d8840fda5272097aacb7f137c9e1d64a374da
Reviewed-on: https://chromium-review.googlesource.com/441316
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>