CHROMIUM: net: tcp: Export tcp_nuke_addr
Otherwise compilation may fail if IPv6 is built as module.

ERROR: "tcp_nuke_addr" [net/ipv6/ipv6.ko] undefined!

Fixes: c7c3ec4903d3 ("net: socket ioctl to reset connections matching local address")
BUG=chromium:583462
TEST=None (build)

Original-Change-Id: Ib18a74aa251cfd3674aa152442a52552e59123b3
Change-Id: I51d2b29ea7b3206ebbce969a121d11a2e7947cf2
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/344369
Commit-Ready: Kevin Cernekee <cernekee@chromium.org>
Tested-by: Kevin Cernekee <cernekee@chromium.org>
Reviewed-by: Guenter Roeck <groeck@google.com>
Reviewed-on: https://chromium-review.googlesource.com/423141
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>