FIXUP: CHROMIUM: kernel device_jail
Builds with CONFIG_USB=m fail with:

security/built-in.o: In function `jail_release':
jail_device.c:(.text+0x594c8): undefined reference to `usb_bus_type'
jail_device.c:(.text+0x594d0): undefined reference to `usb_bus_type'
security/built-in.o: In function `jail_open':
jail_device.c:(.text+0x596b8): undefined reference to `usb_bus_type'
jail_device.c:(.text+0x596c0): undefined reference to `usb_bus_type'
jail_device.c:(.text+0x59708): undefined reference to
`usb_driver_release_interface'
security/built-in.o: In function `add_jail_device':
(.text+0x59898): undefined reference to `usb_bus_type'
security/built-in.o: In function `add_jail_device':
(.text+0x598a0): undefined reference to `usb_bus_type'

While it might be possible to make the new driver buildable as module,
usb_bus_type is not exported. Exporting it seems to be a bad idea, since
it is only used from the usb subsystem and probably not exported on
purpose. It might be possible to use usb_find_interface() instead
of bus_find_device(), but that would be a more complex change, and I
don't know if that is feasible. For now, just make the code dependent
on USB=y.

Change-Id: I77b88b4c98a0ac73a017524dc32a7bf21cce09f4
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/440486
Reviewed-by: Dylan Reid <dgreid@chromium.org>