FIXUP: CHROMIUM: tpm: cr50_spi: Wake cr50 after resume
If CONFIG_PM_SLEEP is not enabled, we see the following build failure.

vers/char/tpm/cr50_spi.c: In function 'cr50_spi_resume':
drivers/char/tpm/cr50_spi.c:370:2: error:
	implicit declaration of function 'cr50_resume'

The following warning is also seen.

drivers/char/tpm/cr50_spi.c: At top level:
drivers/char/tpm/cr50_spi.c:358:12: warning:
	'cr50_spi_resume' defined but not used

BUG=b:37366209
TEST=build and boot

Signed-off-by: Guenter Roeck <groeck@chromium.org>

Change-Id: I35ac7adb4b233e0988e20b9bb8de35d7fe5857c4
Reviewed-on: https://chromium-review.googlesource.com/489365
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Andrey Pronin <apronin@chromium.org>
(cherry picked from commit 6a67271c698e4813b4a348b57d8e55c96405e3f1)
Reviewed-on: https://chromium-review.googlesource.com/491946
Commit-Queue: Andrey Pronin <apronin@chromium.org>
Tested-by: Andrey Pronin <apronin@chromium.org>