FIXUP: CHROMIUM: tpm: control deep-sleep for cr50
Fix build problems such as

ERROR: "cr50_control_deep_sleep" [drivers/char/tpm/cr50_spi.ko] undefined!
ERROR: "tpm_transmit_cmd" [drivers/char/tpm/cr50.ko] undefined!

The first problem is seen because functions from cr50 common code are
not exported. The latter problem is seen because tpm_transmit_cmd is
not exported, and should not be exported, from the core kernel code.

While at it, also drop the useless __maybe_unused markers attached to
the global functions.

BUG=chromium:681997
TEST=Build x86_64:allmodconfig and xtensa:allmodconfig

Change-Id: Id9d6593edddb14e5fb5fea36bdacaa46ddfbf4d9
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/430299
Reviewed-by: Andrey Pronin <apronin@chromium.org>